### ISSUE TITLE
No highlight select item in auto fix menu

### ISSUE THREAD

**Issue by t7yang** [oscarmcm/ocean-space#1]
<img width="276" alt="no-highlight" src="https://user-images.githubusercontent.com/4502661/43559305-2c14ff04-9640-11e8-8d28-577cc2ba944b.png">

**Comment by oscarmcm** [comment]
Hi @t7yang you know how I can reproduce this error? you mean with _"auto fix menu"_ something like this?
<img width="711" alt="imagen" src="https://user-images.githubusercontent.com/2553459/43593583-6eaebdba-9635-11e8-9544-ab9b8e4da797.png">

**Comment by t7yang** [comment]
it is actually quick fix menu, which `ctrl + .`
<img width="168" alt="show-quick-fix" src="https://user-images.githubusercontent.com/4502661/43594020-c2cbdaba-96ab-11e8-937d-732456ddfe21.png">

**Comment by oscarmcm** [comment]
Hey @t7yang this is how it looks for me, which OS are you using?
<img width="342" alt="imagen" src="https://user-images.githubusercontent.com/2553459/43617008-b074173a-967c-11e8-9187-c69750f38251.png">

**Comment by t7yang** [comment]
`"window.titleBarStyle": "custom",` this setting change the UI render method, which currently affect on windows on both stable and insiders channel. I'm switching several themes, but only ocean space can not show selecting highlight :(

**Comment by oscarmcm** [comment]
yes, also i have `custom` title bar in my settings, but it seem to be as my prev comment, switched several times and ended with the same visual output. Also I'm usign `macOS` are you using `Windows`?

**Comment by t7yang** [comment]
are using windows OS / OS X? (your screenshot is OS X) custom title bar only affect on windows. It seem to be OK on stable, but broke on insiders

**Comment by oscarmcm** [comment]
so, its a Windows bug, let me check how i can fix it

**Comment by t7yang** [comment]
I already figure out how to fix the problems, below is the summary of issues that currently facing.

## Scrollbar
Background color should have difference lightness and MUST with transparency. Here the example I increase the lightness 20% in each level (from background to activeBackground) and with 60% transparency:

```json
{
        "scrollbarSlider.background": "#25334480",
        "scrollbarSlider.activeBackground": "#5D83AA80",
        "scrollbarSlider.hoverBackground": "#415B7780"
}
```

## Editor suggestion
Same problem. Highlight color does not light enough to make it clear. Here I increase 20% of lightness, look great at stable and insiders.

```json
{
        "editorSuggestWidget.selectedBackground": "#2F3654"
}
```

## File explorer
Same again. `list.activeSelectionBackground` need more lightness than `sideBar.background`.

🙏

**Comment by oscarmcm** [comment]
Hey @t7yang thanks for your help, I've published a new version, let me know if something isn't working as excepted, and feel free to open a new issue :)
